name: Stable Release Funtuna
on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - '__Release/**'
  #     - '__Binaries/**'
  #     - '.github/workflows/repack-and-release.yml'
  # schedule:
  #   - cron: "0 15 * * *"

jobs:
  check-binaries:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Check file existence"
        uses: andstor/file-existence-action@v1
        with:
          files: "__Binaries/BOOT.ELF,__Binaries/CFG.ELF,__Binaries/USBD.IRX,__Binaries/USBHDFSD.IRX,__Binaries/ULE.ELF,__Binaries/LAUNCHELF.CNF,__Binaries/POWEROFF.ELF,__Binaries/icon.sys,__Binaries/SYSTEM.icn,__Release/!Funtuna-Basic/BOOT/FUNTUNA.CNF"
          allow_failure: true

  Repack_and_Release:
    runs-on: ubuntu-24.04
    needs: check-binaries
    steps:
      - name: Checkout code for release
        uses: actions/checkout@v3

      - name: Place binaries at specific locations
        run: |
          destinations=(
            "../__Release/!Funtuna-Basic/BOOT"
            "../__Release/!Funtuna-Clean/BOOT"
            "../__Release/!Funtuna-Basic - Light/BOOT"
          )
          for dest in "${destinations[@]}"; do
            mkdir -p "$dest"
            cp __Binaries/BOOT.ELF "$dest"
            cp __Binaries/CFG.ELF "$dest"
            cp __Binaries/LAUNCHELF.CNF "$dest"
            cp __Binaries/POWEROFF.ELF "$dest"
            cp __Binaries/USBD.IRX "$dest"
            cp __Binaries/USBHDFSD.IRX "$dest"
            cp __Binaries/ULE.ELF "$dest"
            cp __Binaries/SYSTEM.icn "$dest"
            cp __Binaries/icon.sys "$dest"
          done

      - name: Zip folder
        run: |
          cd __Release
          SCH=${GITHUB_SHA::7}
          echo commit $SCH >>commit.txt
          TARGET="FunTuna-Release-$SCH.zip"
          echo "Creating archive: $TARGET"
          zip -r "$TARGET" *
          ls -R

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: FunTuna
          path: "__Release/*.zip"

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest automated Repack"
          files: "__Release/*.zip"

  generate-manifest:
    runs-on: ubuntu-24.04
    needs: check-binaries
    steps:
      - name: Checkout package
        uses: actions/checkout@v3

      - name: Generate manifest
        run: |
          ls -R __Release