name: Update uLaunchELF

on:
  workflow_dispatch:
  repository_dispatch:
    types: [Component_update]

jobs:
  rewrite-jsom:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSHPAT }}

      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Update wLaunchELF_ISR
        run: |
          echo "Downloading BOOT.ELF from the latest release..."
          wget https://github.com/israpps/wLaunchELF_ISR/releases/download/latest/BOOT.ELF -O __Binaries/ULE.ELF
          echo "Copying BOOT.ELF to the release directory..."
          cp __Binaries/ULE.ELF __Release/ULE_psu.ELF

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update uLaunchELF 4.43x_isr'
          add: |
            __Binaries/*
            __Release/*